### ISSUE TITLE
About usage instructions

### ISSUE THREAD

**Issue by CMXX648** [LeoBel0799/Visual-Heart-Estimation#2]
Hello, I am very interested in your article about ECG visual recognition. But I don't know how to use and run it. Can you provide a user manual? Thank you!

**Comment by LeoBel0799** [comment]
Hi,
I am still in development phase. At the end of the project I will publish
the Webapp and I will provide an user manual.
I can tell you that will be available on a normal IP address.



Il Lun 22 Gen 2024, 17:29 CMXX648 ***@***.***> ha scritto:

**Comment by CMXX648** [comment]
Okay, then I wish you all the best in your development
